# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Image

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CdnImageUploadCheckReq(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCdnImageUploadCheckReq(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CdnImageUploadCheckReq()
        x.Init(buf, n + offset)
        return x

    # CdnImageUploadCheckReq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CdnImageUploadCheckReq
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Lemon.Auth.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CdnImageUploadCheckReq
    def ContentMd5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from Md5Content import Md5Content
            obj = Md5Content()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CdnImageUploadCheckReqStart(builder): builder.StartObject(2)
def CdnImageUploadCheckReqAddToken(builder, token): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)
def CdnImageUploadCheckReqAddContentMd5(builder, contentMd5): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(contentMd5), 0)
def CdnImageUploadCheckReqEnd(builder): return builder.EndObject()
