# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Image

class CdnImageFetchStatus(object):
    Success = 0
    FailUnknown = 1
    FailInvalidToken = 2
    FailNoSuchImage = 3

