# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Image

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CdnImage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCdnImage(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CdnImage()
        x.Init(buf, n + offset)
        return x

    # CdnImage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CdnImage
    def CdnId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CdnImageStart(builder): builder.StartObject(1)
def CdnImageAddCdnId(builder, cdnId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(cdnId), 0)
def CdnImageEnd(builder): return builder.EndObject()
