# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Image

class CdnImageUploadCheckStatus(object):
    Success = 0
    SuccessUncached = 1
    SuccessCached = 2
    FailUnknown = 3
    FailInvalidToken = 4

