# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Image

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NetworkImage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNetworkImage(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NetworkImage()
        x.Init(buf, n + offset)
        return x

    # NetworkImage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NetworkImage
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def NetworkImageStart(builder): builder.StartObject(1)
def NetworkImageAddUrl(builder, url): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)
def NetworkImageEnd(builder): return builder.EndObject()
