# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Contact

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FetchContactReq(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFetchContactReq(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FetchContactReq()
        x.Init(buf, n + offset)
        return x

    # FetchContactReq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FetchContactReq
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Lemon.Auth.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FetchContactReqStart(builder): builder.StartObject(1)
def FetchContactReqAddToken(builder, token): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)
def FetchContactReqEnd(builder): return builder.EndObject()
