# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Contact

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UpdateContactFlagReq(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUpdateContactFlagReq(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UpdateContactFlagReq()
        x.Init(buf, n + offset)
        return x

    # UpdateContactFlagReq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UpdateContactFlagReq
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # UpdateContactFlagReq
    def NewFlag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def UpdateContactFlagReqStart(builder): builder.StartObject(2)
def UpdateContactFlagReqAddId(builder, id): builder.PrependUint32Slot(0, id, 0)
def UpdateContactFlagReqAddNewFlag(builder, newFlag): builder.PrependUint16Slot(1, newFlag, 0)
def UpdateContactFlagReqEnd(builder): return builder.EndObject()
