# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Contact

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UploadAvatarReq(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUploadAvatarReq(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UploadAvatarReq()
        x.Init(buf, n + offset)
        return x

    # UploadAvatarReq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UploadAvatarReq
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Lemon.Auth.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UploadAvatarReq
    def Avatar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Lemon.Image.CdnImage import CdnImage
            obj = CdnImage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def UploadAvatarReqStart(builder): builder.StartObject(2)
def UploadAvatarReqAddToken(builder, token): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)
def UploadAvatarReqAddAvatar(builder, avatar): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(avatar), 0)
def UploadAvatarReqEnd(builder): return builder.EndObject()
