# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Contact

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UploadAvatarResp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUploadAvatarResp(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UploadAvatarResp()
        x.Init(buf, n + offset)
        return x

    # UploadAvatarResp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UploadAvatarResp
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def UploadAvatarRespStart(builder): builder.StartObject(1)
def UploadAvatarRespAddStatus(builder, status): builder.PrependUint8Slot(0, status, 0)
def UploadAvatarRespEnd(builder): return builder.EndObject()
