# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Auth

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AccountStatusPush(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAccountStatusPush(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AccountStatusPush()
        x.Init(buf, n + offset)
        return x

    # AccountStatusPush
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AccountStatusPush
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def AccountStatusPushStart(builder): builder.StartObject(1)
def AccountStatusPushAddStatus(builder, status): builder.PrependUint8Slot(0, status, 0)
def AccountStatusPushEnd(builder): return builder.EndObject()
