# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Auth

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AuthToken(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAuthToken(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AuthToken()
        x.Init(buf, n + offset)
        return x

    # AuthToken
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AuthToken
    def Content(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def AuthTokenStart(builder): builder.StartObject(1)
def AuthTokenAddContent(builder, content): builder.PrependUint32Slot(0, content, 0)
def AuthTokenEnd(builder): return builder.EndObject()
