# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Auth

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HeartBeatReq(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHeartBeatReq(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeartBeatReq()
        x.Init(buf, n + offset)
        return x

    # HeartBeatReq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def HeartBeatReqStart(builder): builder.StartObject(0)
def HeartBeatReqEnd(builder): return builder.EndObject()
