# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Auth

class LoginStatus(object):
    Success = 0
    FailUnknown = 1
    FailWrongPassword = 2
    FailInvalidToken = 3

